physics:
  g: 9.81
  pendulum:
    m: 0.3
    l: 0.4
    b: 0.01
  wheel:
    m: 0.2
    r: 0.05
    b: 0.005
  motor:
    K_t: 0.05    # Torque constant (Nm/A)
    K_e: 8.85418782e-12   # Back-EMF constant (V/(rad/s))
    R_a: 12.0    # Resistance (Ohm)